---
version: '3' # https://taskfile.dev
dotenv: [ '.env' ]
################################################################################################
vars:
  TASKFILE_REMOTE_NAME: "nnosal/Taskfiles"
  TASKFILE_REMOTE_FILE: "Taskfile.yml" # "docker/ci.Taskfile.yml"
includes:
  # Load main task-collection
  _: { taskfile: "https://raw.githubusercontent.com/{{.TASKFILE_REMOTE_NAME}}/refs/heads/main/{{.TASKFILE_REMOTE_FILE}}", flatten: true }
  # Exemple: other interesting project
  _id:ansible: { taskfile: "https://raw.githubusercontent.com/megabyte-labs/install.doctor/refs/heads/master/.config/taskfiles/ansible/Taskfile.yml", optional: true }
  _zlb:vault: { taskfile: "https://raw.githubusercontent.com/zloeber/taskfiles/refs/heads/main/tasks/Taskfile.vault.yml", optional: true }
  _ffx:rclone: { taskfile: "https://raw.githubusercontent.com/frozenfoxx/taskfiles/refs/heads/main/rclone.tasks.yml", optional: true }
  #_setola:ssl: { taskfile: "https://raw.githubusercontent.com/setola/task-files/refs/heads/main/ssl/Taskfile.yml", optional: true } # LINUX ONLY
  ################################################################################################

task:
  default:
    task: echo

  # ADD MY OWN...
  my_new_task:
    cmd: echo HELLO WORLD !
  my_new_task2:
    cmds: [ "echo 1", "echo 2", "echo 3", "echo GO!" ]
