version: "3"

################################################################################################
#
# ref:
#   - https://taskfile.dev/#/usage
# Project Template inspired from: github.com/better-sre
#
################################################################################################

#
# sub namespace: https://taskfile.dev/#/usage?id=including-other-taskfiles
#
includes:
  test:
    taskfile: ./common/test.Taskfile.yml
    dir: .

  docker_ci:
    taskfile: ./docker/ci.Taskfile.yml
    dir: ./docker/

  #_docker:
  #  aliases: [ 'dokr' ]
  #  taskfile: ./docker/
  #  dir: ./docker/
  #  optional: true
    
  #os:
  #  taskfile: ./Taskfile_{{OS}}.yml
  #  dir: .
  #  optional: true

################################################################################################

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

#
# global env: https://taskfile.dev/#/usage?id=environment-variables
#
env:
  ENV1: testing-env

# env file:
#dotenv:
#  - .env

################################################################################################

# task groups:
tasks:
  default:
    cmds:
      - task: echo

  #init:
  #  cmds:
  #    - cp .env.local .env

  test-sample:
    description: From recipe repo -- test "Taskfile.sample.yml"
    cmds:
      - task -t Taskfile.sample.yml --clear-cache
      - task -t Taskfile.sample.yml --download -y
      - task -t Taskfile.sample.yml --list-all
      - task -t Taskfile.sample.yml # echo

  echo:
    cmds:
      - echo "hello world"

  ################################################################################

  pull:
    aliases: [ "pl" ]
    cmds:
      - git config pull.rebase false
      - git pull origin main

  fetch:
    aliases: [ "f" ]
    cmds:
      - git fetch
      - git rebase
      - git merge origin/main

  quick:
    aliases: [ "q" ]
    cmds:
      - task: commit
      #- task: pull
      - task: push

  commit:
    aliases: [ "c" ]
    cmds:
      - git add .
      - |
        git commit -m 'chore: update' --no-verify
    ignore_error: true

  push:
    aliases: [ "p" ]
    cmds:
      - git push origin main --tags
      - repo_url=`git remote -v | grep push | awk -F ":" '{print $2}' | awk -F ".git" '{print "https://github.com/"$1}'`; open $repo_url
