version: "3"
#dotenv: [ '.env' ]

################################################################################################
#
# ref:
#   - https://taskfile.dev/#/usage
# Project Template inspired from: github.com/better-sre
#
################################################################################################

#
# sub namespace: https://taskfile.dev/#/usage?id=including-other-taskfiles
#
includes:
  tools:
    taskfile: ./common/tools.Taskfile.yml
    dir: .

  python:
    taskfile: ./common/python.Taskfile.yml
    dir: .

  git:
    taskfile: ./common/git.Taskfile.yml
    dir: .

  docker:
    aliases: [ 'dkr' ]
    taskfile: ./docker/Taskfile.yml
    #optional: true
  docker:ci:
    taskfile: docker/ci.Taskfile.yml
  docker:compose:
    aliases: [ 'dkc' ]
    taskfile: docker/compose.Taskfile.yml
  docker:swarm:
    aliases: [ 'dks' ]
    taskfile: docker/swarm.Taskfile.yml

  os:
    taskfile: ./os/{{OS}}.Taskfile.yml
    dir: .
    optional: true

################################################################################################

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

#
# global env: https://taskfile.dev/#/usage?id=environment-variables
#
env:
  ENV1: testing-env

# env file:
#dotenv:
#  - .env

################################################################################################

# task groups:
tasks:
  #init:
  #  cmds:
  #    - cp .env.local .env

  list:
    desc: List all tasks with fuzzy-search (fzf)
    silent: true
    preconditions:
    - sh: 'jq --version'
      msg: 'Require: jq for verification'
    - sh: 'fzf --version'
      msg: 'Require: fzf for lazy-search'
    cmd: tasks=$(task -aj | jq -r '.tasks[].name' | fzf --layout reverse --header='CTRL-c or ESC to quit' --preview="task -lj | jq -r '.tasks[] | select(.name == \"{}\")'" --preview-label='[Task details]'); test $tasks && task $tasks || echo >/dev/null

  run-internal:
    desc: "Execute some internal task: task run -- db:down"
    cmd:
      task: "{{.CLI_ARGS}}"
    requires:
      vars: [ CLI_ARGS ]

  test-sample:
    description: From recipe repo -- test "Taskfile.sample.yml"
    cmds:
    - task -t Taskfile.sample.yml --clear-cache
    - task -t Taskfile.sample.yml --download -y
    - task -t Taskfile.sample.yml --list-all
    - task -t Taskfile.sample.yml list # echo

  echo:
    cmds:
    - echo "hello world"
  ################################################################################
