version: "3"
dotenv: [ '.env' ]

################################################################################################
#
# ref:
#   - https://taskfile.dev/#/usage
# Project Template inspired from: github.com/better-sre
#
################################################################################################

#
# sub namespace: https://taskfile.dev/#/usage?id=including-other-taskfiles
#
includes:
  tools:
    taskfile: ./common/tools.Taskfile.yml
    dir: .

  python:
    taskfile: ./common/python.Taskfile.yml
    dir: .

  #_docker:
  #  aliases: [ 'dokr' ]
  #  taskfile: ./docker/
  #  dir: ./docker/
  #  optional: true

  os:
    taskfile: ./os/{{OS}}.Taskfile.yml
    dir: .
    optional: true

################################################################################################

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

#
# global env: https://taskfile.dev/#/usage?id=environment-variables
#
env:
  ENV1: testing-env

# env file:
#dotenv:
#  - .env

################################################################################################

# task groups:
tasks:
  default:
    cmds:
    - task: echo

  #init:
  #  cmds:
  #    - cp .env.local .env

  test-sample:
    description: From recipe repo -- test "Taskfile.sample.yml"
    cmds:
    - task -t Taskfile.sample.yml --clear-cache
    - task -t Taskfile.sample.yml --download -y
    - task -t Taskfile.sample.yml --list-all
    - task -t Taskfile.sample.yml # echo

  echo:
    cmds:
    - echo "hello world"
  ################################################################################
