name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl bash
          source .env && task --version
          # curl -fsSL https://taskfile.dev/install.sh | sh -s -- -d -b /usr/local/bin

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run Task to build and push Docker image
        run: |
          source .env
          export TASK_X_REMOTE_TASKFILES=1
          task --download -y
          task docker_ci:build_push \
            SRC_DIR="${{ github.workspace }}" \
            REGISTRY="ghcr.io" \
            REPOSITORY="${{ github.repository }}" \
            SRC="${{ github.workspace }}"
